name: check all tests
on: pull_request
jobs: 
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps: 
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
